#!/usr/bin/env bash

#
# Redirect all traffic to the demo is resyncing
#
mv "public/.htaccess" "public/.htaccess-backup"
cp "public/.htaccess-updating" "public/.htaccess"

function restore_htaccess () {
	rm "public/.htaccess"
	mv "public/.htaccess-backup" "public/.htaccess"
}

#
# Check out the latest build of the recipe.
#
composer update --no-interaction

if [ $? -eq 0 ]; then
	# Drop the current database, run dev/build to repopulate the database.
	TABLES=$(mysql silvershopcore -e 'show tables' | awk '{ print $1}' | grep -v '^Tables' )

	for t in $TABLES
	do
		echo "Deleting $t table from database..."
		mysql silvershopcore -e "DROP TABLE $t"
	done

	php ./app/src/cli-script-docker-fixed.php dev/build
	php ./app/src/cli-script-docker-fixed.php dev/tasks/PopulateShopTask

	restore_htaccess
else
	# restore htaccess
	restore_htaccess
fi
