---
Name: app
---
SilverShop\Model\Order:
  modifiers:
    - SilverShop\Shipping\ShippingFrameworkModifier
SilverShop\Page\CheckoutPage:
  steps:
    'membership': 'SilverShop\Checkout\Step\Membership'
    'contactdetails': 'SilverShop\Checkout\Step\ContactDetails'
    'shippingaddress': 'SilverShop\Checkout\Step\Address'
    'billingaddress': 'SilverShop\Checkout\Step\Address'
    'shippingmethod': 'SilverShop\Shipping\Checkout\Step\CheckoutStepShippingMethod'
    'paymentmethod': 'SilverShop\Checkout\Step\PaymentMethod'
    'summary': 'SilverShop\Checkout\Step\Summary'